# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:4

pipelines:
  default:
    - parallel:
      - step:
          name: 'Step 1'
          run-ons:
            - 'self.hosted
            - 'linux'
            - 'estudos.test'
          script:
            - echo "This step will run on a self hosted runner.";
            - docker 
            - docker compose
      - step:
          name: 'Step 2'
          script:
            - echo "This step will run on Atlassian's infrastructure as usual.";
